### ISSUE TITLE
`Cookie` header should use semicolon ";" to separate cookies

### ISSUE THREAD

**Issue by adamwight** [CrowdHailer/cookie.ex#1]
https://github.com/CrowdHailer/cookie.ex/blob/e26fd60a52db82c4729744bbc3da9f31524739c2/lib/cookie.ex#L114

Apologies if I'm misreading the [RFC](https://tools.ietf.org/html/rfc6265#section-4.2.1), but it looks like we're supposed to use the semicolon to separate cookies?

**Comment by indocomsoft** [comment]
Agreed, I have been using `|> Cookie.serialize() |> String.replace(", ", "; ")`. I don't mind submitting a PR for this

**Comment by CrowdHailer** [comment]
Does using a comma break anything. A comma is the standard separator for any header that takes multiple values.
Several server libraries split on semi colon or comma?

**Comment by CrowdHailer** [comment]
To add context to my above comment

> A recipient MAY combine multiple header fields with the same field
   name into one "field-name: field-value" pair, without changing the
   semantics of the message, by appending each subsequent field value to
   the combined field value in order, separated by a comma.

https://tools.ietf.org/html/rfc7230#section-3.2.2

By the way, if you have an example where using a comma didn't work as expected I will happily merge the PR

**Comment by indocomsoft** [comment]
At least it breaks on Microsoft-based servers, e.g. my school's ADFS (Microsoft's single-sign-on solution) and ASP pages. I did not test it on other servers.

From what I understand, RFC7230 handles the general case of HTTP headers, but the Cookie protocol is specified with an earlier RFC6265, which specified semicolon separator for each cookie key-value pair (https://tools.ietf.org/html/rfc6265#section-4.2.1) as mentioned by @adamwight. RFC7230 also mentioned about `Set-Cookie` header being a special case that does not use combined field value, so I assume that this applies to the `Cookie` header as well.

MDN also specifies semicolon: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie

Plus, using comma would break `Plug.Conn.Cookies` too which splits by semicolon only: https://github.com/elixir-plug/plug/blob/v1.10.3/lib/plug/conn/cookies.ex#L17

**Comment by CrowdHailer** [comment]
Thanks for the context. I will merge

**Comment by CrowdHailer** [comment]
New version on hex. 0.1.2

**Comment by indocomsoft** [comment]
Thank you for the quick turnaround! This library has been really useful for me
